# Generated by cucumber-sinatra. (2014-10-08 15:45:41 +0100)

ENV['RACK_ENV'] = 'test'

ENV['TZ'] = 'GMT'

require File.join(File.dirname(__FILE__), '..', '..', 'app/router.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = ConfessionBoard

class ConfessionBoardWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ConfessionBoardWorld.new
end
